### ISSUE TITLE
I don't know why this exists

### ISSUE THREAD

**Issue by Ristarg** [boyEstrogen/Anime-Girls-Holding-Programming-Books#3]
But I'm loving every bit of it. God bless.

**Comment by hanss314** [comment]
Same here, I forked it.

**Comment by ioncodes** [comment]
Same 😂

**Comment by eivindml** [comment]
Weirdest Github repo yet 🤣

**Comment by Morwenn** [comment]
Thanks for the repo, it gave my inspiration for a new profile pic :3
