### ISSUE TITLE
This book is not being held

### ISSUE THREAD

**Issue by redstonedash** [boyEstrogen/Anime-Girls-Holding-Programming-Books#39]
https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/blob/master/C%2B%2B/cirno_teaches_c%2B%2B.jpg

this is an anime girl on a book not an anime girl holding a book.

**Comment by 32th-System** [comment]
recursion is very important on a good programming book

**Comment by hakaba-hitoyo** [comment]
![cirno_teaches_c](https://user-images.githubusercontent.com/2155555/49536700-7e5fd900-f90a-11e8-9fcc-4db1b927ec7f.jpg)

**Comment by Akaricchi** [comment]
@hakaba-hitoyo lgtm

**Comment by redstonedash** [comment]
so i have submitted a pull request to get this fixed, thanks @hakaba-hitoyo

**Comment by Unihedro** [comment]
status: complete
