### ISSUE TITLE
How do I delete someone else's repo?

### ISSUE THREAD

**Issue by Ale32bit** [boyEstrogen/Anime-Girls-Holding-Programming-Books#43]
/s

**Comment by ritiek** [comment]
nani?!

**Comment by gagantous** [comment]
what...

**Comment by RustyRaptor** [comment]
Change question to "How do I delete someone else's repo and all related forks" because just deleting this one would do pretty much nothing.

**Comment by qub1750ul** [comment]
Try cloning and then deleting the files
