### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by WWRS** [boyEstrogen/Anime-Girls-Holding-Programming-Books#5]
These files are duplicates, as printed by a script that finds files of the same size. Note that the right-hand column is a list of the earliest file for which each item in the left-hand column is the same as.

In other words, remove the files in the left-hand column only.

```
1487048406652.png 1486598488282.png
1487048603023.jpg 1486599224741.jpg
1487048693272.png 1486598722761.png
1488082463839.jpg 1486596762819.jpg
1488085187313.jpg 1487048522695.jpg
1488089263487.png 1487048296507.png
1488092191937.png 1487131622400.png
1492863307737.png 1486598488282.png
1492871032584.png 1486596518303.png
1492872720853.jpg 1486599290037.jpg
1492873876180.jpg 1486597116031.jpg
1492873957522.png 1486596094290.png
1492874108049.jpg 1486600180056.jpg
```

**Comment by boyEstrogen** [comment]
file names have been changed and im pretty sure someone cleaned up the dupicates a while ago. Thanks for pointing it out though
