### ISSUE TITLE
PHP必须得有姓名

### ISSUE THREAD

**Issue by kiritokun07** [boyEstrogen/Anime-Girls-Holding-Programming-Books#55]
Php is the best language in the world

**Comment by MWGuy** [comment]
If you love PHP, then you must love [jphp](https://github.com/jphp-group/jphp)

**Comment by qcminecraft** [comment]
Waiting for merging...
https://github.com/boyEstrogen/Anime-Girls-Holding-Programming-Books/pull/63

![PHPER](https://user-images.githubusercontent.com/25388328/57572134-f8ac0080-7448-11e9-916a-ee5fe23f223a.png)

**Comment by Asday** [comment]
PHP isn't so much a programming language...  It's more like a catastrophe happening in slow motion, codified in some horrible mix of every actual programming language that was popular at the time.

I'm not sure this belongs in the repo.  PHP is just too bad.

**Comment by qcminecraft** [comment]
> PHP isn't so much a programming language... It's more like a catastrophe happening in slow motion, codified in some horrible mix of every actual programming language that was popular at the time.
> 
> I'm not sure this belongs in the repo. PHP is just too bad.

Agree. Because "PHP is the best" is just a joke. XD
But you have to admit, some website like wikipedia are by php and it's friendly to `new programmers` like `Chisaki chan` in the picture.

**Comment by qcminecraft** [comment]
> PHP isn't so much a programming language... It's more like a catastrophe happening in slow motion, codified in some horrible mix of every actual programming language that was popular at the time.
> 
> I'm not sure this belongs in the repo. PHP is just too bad.

Anyway, this is just a repo for entertainment, not for business, ry?

**Comment by kiritokun07** [comment]
"php" is just for fun,thanks~
