### ISSUE TITLE
Lacking pictures with the Intel Software Developer Manual

### ISSUE THREAD

**Issue by dysoco** [boyEstrogen/Anime-Girls-Holding-Programming-Books#57]
I want one to use as avatar in my computer architecture class and kill my reputation.

**Comment by Asday** [comment]
[Be the change you want to see](https://www.gimp.org/).

**Comment by dysoco** [comment]
> [Be the change you want to see](https://www.gimp.org/).

Sadly I'm banned from doing graphic design because of how terrible I am but I might give it a try.

**Comment by Asday** [comment]
It's art, not graphic design.  :)

I'm ready and waiting to put a :+1: on your PR.

**Comment by boyEstrogen** [comment]
ill add it if someone makes it, but please dont use the issues tab to request edits
