### ISSUE TITLE
Consider renaming to "fictional Japanese girls holding technical books"

### ISSUE THREAD

**Issue by Asday** [boyEstrogen/Anime-Girls-Holding-Programming-Books#59]
As pointed out in #58, there are non-programming books, and there are also non-anime girls contained within this repository.

While one _could_ remove them, I feel they serve the comfy feel of the repository well.  To maintain accuracy, a renaming would be reasonably sensible.

Renaming the repository is an ok idea, as I don't imagine many people have this cloned and doing regular pulls on it, but simply changing the opening to README may be sufficient.

**Comment by windowsEmmie** [comment]
I feel like approving some non-anime or non-programming images while maintaining the current name wouldn't hurt the overall quality of the repository, as long as stuff like cosplay or 3d doesn't show up outside of the Other or Memes folders. I think as long as you could see these sorts of images popping up in /dpt/ threads, they generally fit the aim of the repository.

A change to the opening of the README would work - I'm sort of hesitant of an overall name change or the establishment of new rules/guidelines, but I think something along the lines of "anime girls holding programming books (and more!)" would be best (the focus remains on anime girls and programming, but other related content is acknowledged).

**Comment by RustyRaptor** [comment]
"change project name to be more inclusive"

**Comment by Asday** [comment]
Very good points have been made, I am now happier in my understanding of the malleability of language.

As an aside; if someone could make something for Toriyama Ubume, my :+1: is waiting.

**Comment by boyEstrogen** [comment]
as long as the character is female presenting, anime-esque (anime plush, jrpg character), and holding a book about math or computers then im fine with adding it to the repo.
