### ISSUE TITLE
Iffy images

### ISSUE THREAD

**Issue by WWRS** [boyEstrogen/Anime-Girls-Holding-Programming-Books#6]
Not programming books:
1486593470742.png (Hard to tell)
1486596328094.jpg (Hard to tell)
1486598631463.png (Not books)
1486603803566.png (Not books)
1488091053284.png (Not books)
1488142077875.png (Not programming)
1488163265926.png (Not programming)
1488175671350.png (Not programming)
1489258609494.jpg
1489258797967.jpg
1489428997720.png
1489897319256.jpg
1492436088183.jpg
1492869982825.jpg (Not programming)
1492872147802.png (Not books)

Quality is different:
1486596925978.jpg
1486600903057.png
1492531818563.png
1492870106236.jpg

Other
1488082578266.jpg (Not anime? No girls)
1486600538102.png (Upside-down)
lain holding programing book.png (Naming?)

What you do with these is your choice.

**Comment by LightningJimmyJoeJohnson** [comment]
1488082578266.jpg is cosplay.

**Comment by karai17** [comment]
And here I thought this was going to be a bunch of images of IF from Neptunia. :(

**Comment by skid9000** [comment]
Same :(

**Comment by boyEstrogen** [comment]
The file names have been changed  and some of these images have been removed all together, some images you pointed out might still be in the repo but its hard to tell which are which now.
