### ISSUE TITLE
The book which Nagato read is not a programming book

### ISSUE THREAD

**Issue by wx257osn2** [boyEstrogen/Anime-Girls-Holding-Programming-Books#66]
The book which Yuki Nagato read in `Unknown/Nagato_Yuki_Reading.jpg` is ["STARPLEX"](https://www.amazon.com/dp/B002TNABI2) , authored by Robert J. Sawyer.  
"STARPLEX" is a science fiction, not a programming book.

Reference:
- [長門さんが読んだ本　第11話『射手座の日』 - 徒然趣味ブログ](http://standalone.blog50.fc2.com/blog-entry-956.html) : Japanese blog. This article identified what she read.

**Comment by Asday** [comment]
I'm inclined to let it slide, seeing as it's a somewhat nerdy book, and it's not edited in.

**Comment by wx257osn2** [comment]
Hmm, that's fine, but if the pic will be remained this repo, I think that the pic should be moved into `Uncategorized` folder from `Unknown`, since we've known the book name and category.

**Comment by Asday** [comment]
:+1: :+1: :+1:

PRs welcome!  :)

**Comment by wx257osn2** [comment]
#67 has fixed this issue.
